### ISSUE TITLE
Validação: Nome do arquivo

### ISSUE THREAD

**Issue by Suniaster** [Suniaster/SB2021-JVM#24]
Conferir nome do arquivo com o atributo SourceFile

**Comment by patonoide** [comment]
Não entendi, já existe um issue para validar o nome do arquivo.

**Comment by Suniaster** [comment]
Essa issue aqui #21 eh outra parada. Pra fazer a validação do nome do arquivo tem que usar o atributo sourcefile. Nessa outra issue a ideia eh soh verificar se o arquivo que ta tentando ler existe mesmo
